import {  useNavigate } from 'react-router-dom';
import style from "../Home/Home.module.css" 
import logoMini from "../../assets/logonata.png"
 
const Terminos = () => {
    const navigate= useNavigate()
    return(
    <>
    <nav className={style.nav}>
        <img className={style.logoMini} onClick={() => navigate("/")} src={logoMini}/>
    <ul className={style.ul}>
        {/* <li className={style.li}>Inicio</li> */}
        {/* <li onClick={() => navigate("/login")} className={style.li}>Ingresar</li> */}
    </ul>
    </nav>
    <br></br><br></br><br></br>
    <div style={{display:"flex",cursor:"pointer",gap:"60px", marginLeft:"50%",transform:"translateX(-50%)"}}>
    <h1 style={{textAlign:"center"}} onClick={() => navigate("/terminos")}>Terminos de servicios</h1>
    <h1 style={{textAlign:"center", color:"grey"}} onClick={() => navigate("/politicas")}>Política de privacidad</h1>
    </div>
    <p style={{whiteSpace:"pre-line", padding:"0px 100px"}}>
      <b>Generales</b><br></br>
Este sitio web (el 'Sitio') es propiedad y está operado por Natalie ('COMPAÑÍA', 'nosotros' o 'nuestro'). Al utilizar el Sitio, usted acepta estar sujeto a estos Términos y condiciones y utilizar el Sitio de acuerdo con estos Términos y condiciones, nuestra Política de Privacidad y cualquier término y condición adicional que pueda aplicarse a secciones específicas del Sitio o a productos y servicios disponibles a través del Sitio o de la COMPAÑÍA. El acceso al Sitio, de cualquier manera, ya sea automatizado o de otra manera, constituye el uso del Sitio y su aceptación de estar sujeto a estos Términos y condiciones.

Nos reservamos el derecho de cambiar estos Términos y condiciones o de imponer nuevas condiciones sobre el uso del Sitio, de vez en cuando, en cuyo caso publicaremos los Términos y condiciones revisados en este sitio web. Al continuar utilizando el Sitio luego de que publiquemos dichos cambios, usted acepta los Términos y condiciones, según se hayan modificado.
<br></br>
<br></br>
<b>Contenido</b><br></br>
Todo contenido en video, audio, imagen, captura o escrito generado en los medios de contacto entre estudiantes y cualquier integrante del equipo de Natalie, así como, redes sociales, página web, correo, llamada y mensajería instantánea podrá ser utilizado para uso exclusivo de contenido, promoción o publicidad, con el fin de dar a conocer los beneficios que se generan al consumir los programas educativos, así como las experiencias positivas por parte de los estudiantes de los programas.
Los medios de contacto de donde saldrá la información pueden ser vía redes sociales, tales como Facebook, Messenger, Whatsapp, Instagram, Tiktok, Youtube. Otros medios de contacto podrán ser Zoom, Skype, página web, correo, o llamada telefónica.
El contenido podrá ser compartido en formatos de video, audio, imágenes y capturas.
El contenido será compartido en redes sociales, vía correo electrónico, página web, video llamadas o mensajería instantánea con el fin de crear contenido informativo sobre los resultados positivos por parte de los estudiantes, así como creación de publicidad con el fin de motivar e inspirar a prospectos interesados en comprar algún programa o ser parte de la comunidad de Natalie.
<br></br>
<br></br>
<b>Derechos de propiedad intelectual</b><br></br>
<b>Nuestra licencia limitada para usted</b><br></br>
Este Sitio y todos los materiales disponibles en el Sitio son propiedad de nosotros y/o nuestros afiliados o licenciantes, y están protegidos por derechos de autor, marcas comerciales y otras leyes de propiedad intelectual. El sitio se proporciona únicamente para su uso personal no comercial. No puede usar el Sitio o los materiales disponibles en el Sitio

de una manera que constituya una infracción de nuestros derechos o que no haya sido autorizada por nosotros. Más específicamente, a menos que esté explícitamente autorizado en estos Términos y condiciones o por el propietario de los materiales, no puede modificar, copiar, reproducir, republicar, cargar, publicar, transmitir, traducir, vender, crear trabajos derivados, explotar o distribuir en cualquier manera o medio (incluso por correo electrónico u otros medios electrónicos) cualquier material del Sitio. Sin embargo, puede, de vez en cuando, descargar y/o imprimir una copia de páginas individuales del Sitio para su uso personal y no comercial, siempre que mantenga intactos todos los avisos de propiedad intelectual y otros avisos de propiedad.
<br></br><br></br>
<b>Su licencia para nosotros</b><br></br>
Al publicar o enviar cualquier material (incluidos, entre otros, comentarios, entradas de blogs, publicaciones en Facebook, fotos y videos) a través del Sitio, grupos de Internet, medios sociales o a cualquier miembro de nuestro personal por correo electrónico, mensaje de texto o de otro modo, usted está representando: (i) que usted es el propietario del material, o está haciendo su publicación o envío con el consentimiento expreso del propietario del material; y (ii) que tiene trece años o más. Además, cuando envíe, envíe por correo electrónico, envíe un mensaje de texto, entregue o publique cualquier material, nos otorga a nosotros, y a cualquier persona autorizada por nosotros, una licencia mundial sin restricciones, perpetua, irrevocable, no exclusiva, para usar, copiar, modificar, transmitir, vender, explotar, crear trabajos derivados de, distribuir y/o realizar públicamente o mostrar dicho material, en todo o en parte, de cualquier manera o medio, ahora conocido o desarrollado en el futuro, para cualquier propósito. La subvención anterior incluirá el derecho de explotar cualquier derecho de propiedad en dicha publicación o envío, incluidos, entre otros, los derechos de copyright, marca comercial, marca de servicio o leyes de patentes bajo cualquier jurisdicción relevante. Además, en relación con el ejercicio de tales derechos, nos otorga a nosotros, y a cualquier persona autorizada por nosotros, el derecho de identificarlo como el autor de cualquiera de sus publicaciones o presentaciones por nombre, dirección de correo electrónico o nombre de usuario, según lo consideremos apropiado.
Usted reconoce y acepta que cualquier contribución originalmente creada por usted para nosotros se considerará como un 'trabajo hecho para contratar' cuando el trabajo realizado esté dentro del alcance de la definición de un trabajo contratado en la Sección 101 de la Ley de Derechos de Autor de los Estados Unidos. según enmendado. Como tal, los derechos de autor de esas obras pertenecerán a la COMPAÑÍA desde su creación. Por lo tanto, se considerará que la COMPAÑÍA es el autor y propietario exclusivo de la misma y tendrá derecho a explotar cualquiera o todos los resultados y procedimientos en cualquier medio, ahora conocido o en el futuro, en todo el universo, a perpetuidad, en todos los idiomas, como la EMPRESA determina. En el caso de que alguno de los resultados y ganancias de sus envíos a continuación no se consideren como un 'trabajo hecho para contratar' bajo la Sección 101 de la Ley de Copyright, según enmendada, por la presente, sin compensación adicional, asignar, transmitir y transferir irrevocablemente a la EMPRESA todos los derechos de propiedad, incluidos, entre otros, todos los derechos de autor y marcas registradas en todo el universo, a perpetuidad en todos los medios, ya sean conocidos o en adelante, a tal material y todo derecho, título e interés en todos esos derechos de propiedad en cada medio, ya sea conocido o en el futuro, en todo el universo, a perpetuidad. Cualquier material publicado que sea reproducciones de trabajos anteriores por usted será copropiedad de nosotros.

Usted reconoce que la COMPAÑÍA tiene el derecho, pero no la obligación de usar y mostrar publicaciones o contribuciones de cualquier tipo y que la EMPRESA puede optar por suspender el uso y la exhibición de dichos materiales (o cualquier parte del mismo), en cualquier momento y por cualquier motivo lo que.
<br></br>
<br></br>
<b>Limitaciones en la vinculación y enmarcación</b><br></br>
Puede establecer un enlace de hipertexto al Sitio siempre que el enlace no indique ni implique ningún patrocinio de su sitio por nosotros o por el Sitio. Sin embargo, usted no puede, sin nuestro permiso previo por escrito, enmarcar o vincular en línea ninguno de los contenidos del Sitio, o incorporar a otro sitio web u otro servicio cualquiera de nuestros materiales, contenidos o propiedad intelectual.
<br></br>
<br></br>
<b>Exclusión de responsabilidades</b><br></br>
En todo el Sitio, podemos proporcionar enlaces y sugerencias a sitios de Internet mantenidos por terceros. Nuestro enlace a tales sitios de terceros no implica un respaldo o patrocinio de dichos sitios, o la información, productos o servicios ofrecidos en o a través de los sitios. Además, ni nosotros ni nuestros afiliados operamos ni controlamos en modo alguno la información, los productos o los servicios que terceros pueden proporcionar en o a través del Sitio o en los sitios web a los que nos vinculamos en el Sitio.

Si corresponde, cualquier opinión, consejo, declaración, servicio, oferta u otra información o contenido expresado o puesto a disposición por terceros, incluidos los proveedores de información, son los de los respectivos autores o distribuidores, y no la COMPAÑÍA. Ni la COMPAÑÍA ni ningún otro proveedor de información garantiza la exactitud, integridad o utilidad de ningún contenido. Además, la COMPAÑÍA no respalda ni es responsable de la precisión y confiabilidad de cualquier opinión, consejo o declaración hecha en cualquiera de los Sitios por parte de un representante autorizado de la COMPAÑÍA mientras actúe en su capacidad oficial.
LA INFORMACIÓN, LOS PRODUCTOS Y LOS SERVICIOS OFRECIDOS EN O A TRAVÉS DEL SITIO Y POR LA COMPAÑÍA Y CUALQUIER SITIO DE TERCEROS SE PROPORCIONAN 'TAL CUAL' Y SIN GARANTÍAS DE NINGUNA CLASE, YA SEAN EXPRESAS O IMPLÍCITAS. HASTA EL GRADO MÁXIMO PERMITIDO DE ACUERDO CON LA LEY APLICABLE, RENUNCIAMOS A TODAS LAS GARANTÍAS, EXPRESAS O IMPLÍCITAS, INCLUIDAS, ENTRE OTRAS, LAS GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD E IDONEIDAD PARA UN PROPÓSITO EN PARTICULAR. NO GARANTIZAMOS QUE EL SITIO O CUALQUIERA DE SUS FUNCIONES SEA ININTERRUMPIDO O LIBRE DE ERRORES, QUE LOS DEFECTOS SE CORREGIRÁN, O QUE CUALQUIER PARTE DE ESTE SITIO, INCLUIDOS LOS TABLONES DE BOLETINES, O LOS SERVIDORES QUE LO HACEN DISPONIBLE, ESTÉN LIBRES DE VIRUS U OTROS COMPONENTES PERJUDICIALES.
NO GARANTIZAMOS NI HACEMOS NINGUNA DECLARACIÓN CON RESPECTO AL USO O LOS RESULTADOS DEL USO DEL SITIO O LOS MATERIALES EN ESTE SITIO O EN SITIOS DE TERCEROS EN TÉRMINOS DE SU CORRECCIÓN, PRECISIÓN, PUNTUALIDAD, CONFIABILIDAD O DE OTRO MODO.

Usted acepta en todo momento defender, indemnizar y mantener indemne a la EMPRESA sus afiliados, sus sucesores, cesionarios, cesionarios y licenciatarios y sus respectivas empresas matrices y filiales, agentes, asociados, funcionarios, directores, accionistas y empleados de cada uno, desde y contra cualquier todos los reclamos, causas de acción, daños, responsabilidades, costos y gastos, incluidos honorarios y gastos legales, que surjan o estén relacionados con el incumplimiento de cualquier obligación, garantía, representación o pacto establecidos en este documento.
<br></br>
<br></br>
<b>Comercio en línea</b><br></br>
Ciertas secciones del Sitio pueden permitirle comprar muchos tipos diferentes de productos y servicios en línea proporcionados por terceros. No somos responsables de la calidad, precisión, puntualidad, fiabilidad o cualquier otro aspecto de estos productos y servicios. Si realiza una compra a un comerciante en el Sitio o en un sitio vinculado por el Sitio, la información obtenida durante su visita a la tienda o sitio en línea de ese comerciante, y la información que usted proporciona como parte de la transacción, como su El comerciante y nosotros podemos recopilar el número de tarjeta de crédito y la información de contacto. Un comerciante puede tener prácticas de privacidad y recopilación de datos que son diferentes a las nuestras. No tenemos responsabilidad u obligación por estas políticas independientes. Además, cuando compra productos o servicios en oa través del Sitio, puede estar sujeto a términos y condiciones adicionales que se aplican específicamente a su compra o uso de dichos productos o servicios. Para obtener más información sobre un comerciante, su tienda en línea, sus políticas de privacidad y / o los términos y condiciones adicionales que puedan aplicarse, visite el sitio web de ese comerciante y haga clic en sus enlaces de información o comuníquese directamente con el comerciante. Usted nos libera a nosotros y a nuestras afiliadas de cualquier daño en que incurra, y acepta no hacer ningún reclamo contra nosotros o ellos, que surjan de su compra o uso de cualquier producto o servicio puesto a disposición por terceros a través del Sitio.
Su participación, correspondencia o trato comercial con cualquier tercero encontrado en o a través de nuestro Sitio, con respecto al pago y la entrega de bienes y servicios específicos, y cualquier otro término, condición, declaración o garantía asociada con tales transacciones, son únicamente entre usted y dicho tercero fiesta. Usted acepta que la COMPAÑÍA no será responsable de ninguna pérdida, daño u otros asuntos de ningún tipo incurridos como resultado de dichos tratos.
Usted acepta ser financieramente responsable de todas las compras que realice usted o alguien que actúe en su nombre a través del Sitio. Usted acepta utilizar el Sitio y comprar servicios o productos a través del Sitio solo con fines legítimos y no comerciales. También acepta no realizar compras con fines especulativos, falsos o fraudulentos o con el fin de anticipar la demanda de un producto o servicio en particular. Usted acepta comprar bienes o servicios solo para usted o para otra persona por la cual está legalmente permitido hacerlo. Al realizar una compra para un tercero que requiere que nos envíe la información personal del tercero a nosotros o a un comerciante, declara que ha obtenido el consentimiento expreso de dicho tercero para proporcionar la información personal de dicho tercero.
Su compra es solo para uso personal. No se permite el intercambio de compras y se considerará no autorizado, un uso infractor de nuestro material protegido por derechos de autor, y puede someter a los infractores a responsabilidad.

Si se rechaza el pago de un curso, nuestro sistema deshabilitará automáticamente el acceso a nuestros materiales premium. (Entendemos. Esto generalmente ocurre porque una tarjeta de crédito caduca). Queremos ayudar a restaurar su acceso, por lo que haremos todo lo posible para contactarlo para ayudar a resolver este problema. Una vez que se resuelva el problema de facturación, restauraremos el acceso.
<br></br>
<br></br>
<b>Funciones interactivas</b><br></br>
Este sitio puede incluir una variedad de características, como tableros de anuncios, registros web, salas de chat y servicios de correo electrónico, que nos permiten recibir comentarios y la interacción en tiempo real entre los usuarios, y otras características que permiten a los usuarios comunicarse con los demás. La responsabilidad de lo que se publica en los tablones de anuncios, registros web, salas de chat y otras áreas públicas de publicación en el Sitio, o enviada a través de cualquier servicio de correo electrónico en el Sitio, recae en cada usuario; usted es el único responsable del material que publica o envía. No controlamos los mensajes, información o archivos que usted u otros pueden proporcionar a través del Sitio. Es una condición de su uso del sitio que no:
Restrinja o inhiba a cualquier otro usuario de usar y disfrutar el Sitio.
Use el sitio para suplantar a cualquier persona o entidad, o declarar falsamente o tergiversar su afiliación con una persona o entidad.
Interfiera o interrumpa cualquier servidor o red utilizada para proporcionar el Sitio o sus características, o desobedecer cualquier requisito, procedimiento, política o regulación de las redes que utilizamos para proporcionar el Sitio.
Use el sitio para instigar o alentar a otros a cometer actividades ilegales o causar lesiones o daños a la propiedad de cualquier persona.
Obtenga acceso no autorizado al Sitio, o a cualquier cuenta, sistema informático o red conectados a este Sitio, por medios tales como piratería informática, extracción de contraseñas u otros medios ilícitos.
Obtenga o intente obtener cualquier material o información a través de cualquier medio que no esté intencionalmente disponible a través de este Sitio.
Use el sitio para publicar o transmitir cualquier tipo de información ilegal, amenazante, abusiva, calumniosa, difamatoria, obscena, vulgar, pornográfica, profana o indecente de cualquier tipo, incluidas, entre otras, las transmisiones que constituyan o fomenten conductas que constituyan un delito, otorgar ascender a responsabilidad civil o violar cualquier ley local, estatal, nacional o internacional.
Use el sitio para publicar o transmitir cualquier información, software u otro material que viole o infrinja los derechos de otros, incluido material que sea una invasión de la privacidad o derechos de publicidad o que esté protegido por derechos de autor, marca comercial u otro derecho de propiedad, o los trabajos derivados con respecto a los mismos, sin antes obtener el permiso del propietario o titular de los derechos.
Use el sitio para publicar o transmitir cualquier información, software u otro material que contenga un virus u otro componente dañino.
Use el sitio para publicar, transmitir o de alguna manera explotar cualquier información, software u otro material con fines comerciales, o que contenga publicidad.
Use el sitio para anunciar o solicitar a cualquier persona que compre o venda productos o servicios, o para hacer donaciones de cualquier tipo, sin nuestra aprobación expresa por escrito.

Reúna con fines de comercialización cualquier dirección de correo electrónico u otra información personal que haya sido publicada por otros usuarios del Sitio.
La COMPAÑÍA puede albergar tableros de mensajes, chats y otros foros públicos en sus Sitios. Cualquier usuario que no cumpla con los términos y condiciones de este Acuerdo puede ser expulsado y se le negará el acceso continuo a los tableros de mensajes, chats u otros foros públicos en el futuro. LA EMPRESA o sus agentes designados pueden eliminar o alterar cualquier contenido creado por el usuario en cualquier momento y por cualquier motivo. Los tableros de mensajes, las charlas y otros foros públicos están destinados a servir como centros de debate para usuarios y suscriptores. La información y el contenido publicado en estos foros públicos pueden ser proporcionados por personal de la COMPAÑÍA, por colaboradores externos de la COMPAÑÍA o por usuarios no conectados con la COMPAÑÍA, algunos de los cuales pueden emplear nombres de usuario anónimos. LA EMPRESA niega expresamente toda responsabilidad y endoso y no hace ninguna representación en cuanto a la validez de cualquier opinión, consejo, información o declaración hecha o mostrada en estos foros por terceros, ni somos responsables de ningún error u omisión en tales publicaciones, ni de hipervínculos. incrustado en cualquier mensaje. Bajo ninguna circunstancia, nosotros, nuestros afiliados, proveedores o agentes seremos responsables por cualquier pérdida o daño causado por su confianza en la información obtenida a través de estos foros. Las opiniones expresadas en estos foros son únicamente las opiniones de los participantes y no reflejan las opiniones de la EMPRESA o cualquiera de sus subsidiarias o afiliadas.
LA EMPRESA no tiene ninguna obligación de controlar el contenido o las publicaciones en los foros, salas de chat u otros foros públicos en los Sitios. Sin embargo, usted reconoce y acepta que tenemos el derecho absoluto de monitorear el mismo a nuestra entera discreción. Además, nos reservamos el derecho de alterar, editar, negarnos a publicar o eliminar publicaciones o contenido, en todo o en parte, por cualquier motivo y a divulgar dichos materiales y las circunstancias que rodean su transmisión a terceros con el fin de satisfacer cualquier ley aplicable, regulación, proceso legal o solicitud gubernamental y para protegernos a nosotros mismos, a nuestros clientes, patrocinadores, usuarios y visitantes.
<br></br>
<br></br>
<b>Registro</b><br></br>
Para acceder a ciertas características del Sitio, podemos solicitarle que proporcione cierta información demográfica, incluyendo su género, año de nacimiento, código postal y país. Además, si elige registrarse para una función en particular del Sitio, como salas de chat, registros web o tableros de anuncios, también se le puede solicitar que se registre con nosotros en el formulario provisto y dicho registro puede requerir que usted se registre. proporcionar información de identificación personal, como su nombre y dirección de correo electrónico. Usted acepta proporcionar información verdadera, precisa, actual y completa acerca de usted como lo indica el formulario de registro del Sitio. Si tenemos motivos razonables para sospechar que dicha información es falsa, inexacta o incompleta, tenemos el derecho de suspender o cancelar su cuenta y de rechazar cualquier uso actual o futuro del Sitio (o cualquier parte del mismo). Nuestro uso de cualquier información de identificación personal que nos proporcione como parte del proceso de registro se rige por los términos de nuestra Política de privacidad.
<br></br>
<br></br>
<b>Contraseñas</b>
<br></br>
Para usar ciertas características del Sitio, necesitará un nombre de usuario y contraseña, que recibirá a través del proceso de registro del Sitio. Usted es responsable de mantener la confidencialidad de la contraseña y la cuenta, y es responsable de todas las actividades (ya sean realizadas por usted o por terceros) que ocurran bajo su contraseña o cuenta. Usted acepta notificarnos inmediatamente sobre cualquier uso no autorizado de su contraseña o cuenta o cualquier otra violación de seguridad, y para asegurarse de que salga de su cuenta al final de cada sesión. No podemos ni nos haremos responsables de ninguna pérdida o daño que surja de la falta de protección de su contraseña o información de cuenta.
<br></br>
<br></br>
<b>Limitación de responsabilidad</b><br></br>
BAJO NINGUNA CIRCUNSTANCIA, INCLUYENDO, PERO SIN LIMITARSE A, NEGLIGENCIA, NOSOTROS, NUESTRA SUBSIDIARIA Y LAS EMPRESAS PADRES O AFILIADAS SERÁN RESPONSABLES DE DAÑOS DIRECTOS, INDIRECTOS, INCIDENTALES, ESPECIALES O CONSECUENCIALES QUE RESULTEN DEL USO O DE LA INCAPACIDAD DE USAR, EL SITIO, INCLUYENDO NUESTRO MENSAJERÍA, BLOGS, COMENTARIOS DE OTROS, LIBROS, CORREOS ELECTRÓNICOS, PRODUCTOS O SERVICIOS, O MATERIALES, PRODUCTOS O SERVICIOS DE TERCEROS DISPONIBLES A TRAVÉS DEL SITIO O POR NOSOTROS DE CUALQUIER FORMA, INCLUSO SI SE ACONSEJA ANTES DE LA PRESENTACIÓN DE LA POSIBILIDAD DE DICHOS DAÑOS. (DEBIDO A QUE ALGUNOS ESTADOS NO PERMITEN LA EXCLUSIÓN O LIMITACIÓN DE DETERMINADAS CATEGORÍAS DE DAÑOS, LA LIMITACIÓN ANTERIOR PUEDE NO APLICAR EN USTED. EN TALES ESTADOS, NUESTRA RESPONSABILIDAD Y LA RESPONSABILIDAD DE NUESTRAS EMPRESAS SUBSIDIARIAS Y DE PADRES O AFILIADAS ESTÁ LIMITADA AL GRADO MÁXIMO PERMITIDO POR DICHA LEY ESTATAL.) USTED RECONOCE Y ACEPTA ESPECÍFICAMENTE QUE NO SOMOS RESPONSABLES DE NINGUNA CONDUCTA DIFAMATORIA, OFENSIVA O ILEGAL DE NINGÚN USUARIO. SI NO ESTÁ SATISFECHO CON EL SITIO, CUALQUIER MATERIAL, PRODUCTO O SERVICIO DEL SITIO, O CON CUALQUIERA DE LOS TÉRMINOS Y CONDICIONES DEL SITIO, SU ÚNICO Y EXCLUSIVO RECURSO ES DEJAR DE USAR EL SITIO Y LOS PRODUCTOS, SERVICIOS Y / O EMPRESA MATERIALES NO ES UN SERVICIO DE ASESORÍA DE INVERSIÓN, NO ES UN ASESOR DE INVERSIÓN Y NO OFRECE ASESORAMIENTO FINANCIERO PERSONALIZADO NI ACTÚA COMO ASESOR FINANCIERO.
EXISTEMOS SOLO CON FINES EDUCATIVOS, Y LOS MATERIALES E INFORMACIÓN CONTENIDA EN EL PRESENTE DOCUMENTO Y EN NUESTROS PRODUCTOS Y SERVICIOS SON SÓLO PARA FINES INFORMATIVOS GENERALES. NINGUNA DE LA INFORMACIÓN PROPORCIONADA POR NOSOTROS TIENE EL FIN DE INVERSIÓN, IMPUESTO, CONTABILIDAD O ASESORAMIENTO LEGAL, COMO UNA OFERTA O SOLICITUD DE UNA OFERTA PARA COMPRAR O VENDER, O COMO RECOMENDACIÓN, ENDOSO O PATROCINIO DE CUALQUIER COMPAÑÍA, SEGURIDAD O FONDO. NUESTRA INFORMACIÓN NO SE DEBERÁ TENER EN CUENTA CON FINES DE TRANSACCIÓN EN VALORES NI EN OTRAS INVERSIONES.
NO OFRECEMOS NI OFRECEMOS ASESORAMIENTO FISCAL, JURÍDICO O DE INVERSIÓN Y USTED ES RESPONSABLE DE CONSULTAR A PROFESIONALES FISCALES, LEGALES O FINANCIEROS ANTES DE ACTUAR EN CUALQUIER INFORMACIÓN PROPORCIONADA POR NOSOTROS. ESTE SITIO ESTÁ CONTINUAMENTE BAJO EL DESARROLLO Y LA COMPAÑÍA NO OFRECE NINGUNA GARANTÍA, IMPLÍCITA O EXPRESA, EN CUANTO A SU EXACTITUD, INTEGRIDAD O APROPIACIÓN PARA CUALQUIER PROPÓSITO.
USTED reconoce y acepta que la EMPRESA O SUS AFILIADOS no han hecho ninguna manifestación y se han basado en los ingresos, gastos, volumen de ventas o rentabilidad potencial futuros que puedan derivarse de la participación en ESTE PROGRAMA.
<br></br>
<br></br>
<b>Terminación</b><br></br>
Podemos cancelar o cancelar su derecho a utilizar el Sitio o cualquier parte del Sitio en cualquier momento sin previo aviso. En caso de cancelación o terminación, ya no está autorizado para acceder a la parte del Sitio afectada por dicha cancelación o terminación. Las restricciones impuestas sobre usted con respecto al material descargado del Sitio, y las renuncias y limitaciones de responsabilidades establecidas en estos Términos de Servicio, seguirán vigentes.
<br></br>
<br></br>
<b>Política de reembolso</b><br></br>
Su compra de un producto o servicio o boleto a un evento puede o no proporcionar ningún reembolso. Cada producto, servicio, evento o curso específico especificará su propia política de reembolso.
<br></br>
<br></br>
<b>Otros</b><br></br>
La Ley de Derechos de Autor Digital Millennium de 1998 (la 'DMCA') ofrece recursos para los propietarios de los derechos de autor que creen que el material que aparece en Internet infringe sus derechos en virtud de la ley de derechos de autor de los Estados Unidos. Si cree de buena fe que los materiales alojados por la COMPAÑÍA infringen sus derechos de autor, usted o su agente pueden enviar a la COMPAÑÍA un aviso solicitando que se elimine el material o se bloquee el acceso a él. Cualquier notificación por parte de un propietario de derechos de autor o una persona autorizada para actuar en su nombre que no cumpla con los requisitos de la DMCA no se considerará notificación suficiente y no se considerará que confiere al conocimiento actual de la EMPRESA hechos o circunstancias de los cuales el material infractor los actos son evidentes. Si cree de buena fe que un aviso de infracción de derechos de autor ha sido presentado incorrectamente en su contra, la DMCA le permite enviar a la COMPAÑÍA un contra aviso. Todos los avisos y avisos contrarios deben cumplir con los requisitos legales vigentes en ese momento impuestos por la DMCA; vea http://www.loc.gov/copyright para más detalles. El agente de derechos de autor de la empresa para recibir notificaciones de reclamos de infracción de derechos de autor o avisos contrarios puede comunicarse al email mostrado en la landing

Este Acuerdo será vinculante y redundará en beneficio de la COMPAÑÍA y nuestros respectivos cesionarios, sucesores, herederos y representantes legales. Ni este Acuerdo ni ningún derecho en virtud del mismo se pueden asignar sin el consentimiento previo por escrito de la COMPAÑÍA. No obstante lo anterior, todos los derechos y obligaciones bajo este Acuerdo pueden ser asignados libremente por la COMPAÑÍA a cualquier entidad afiliada o cualquiera de sus subsidiarias de propiedad absoluta.

Estos Términos de uso se regirán e interpretarán de acuerdo con las leyes de la República de Colombia y cualquier disputa estará sujeta a los entes que regula la materia. Si alguna disposición de este acuerdo fuera ilegal, nula o inaplicable por algún motivo, dicha disposición se considerará separable de este acuerdo y no afectará la validez y aplicabilidad de las disposiciones restantes.
<br></br>
<br></br>
<b>Renuncia</b><br></br>
Aunque es muy poco probable, esta política se puede cambiar en cualquier momento a nuestra discreción. Si debemos actualizar esta política, publicaremos las actualizaciones en esta página en nuestro sitio web.
Si tiene alguna pregunta o inquietud sobre nuestra política de privacidad, envíela al email mostrado en la landing

    </p>
    </> 
  )
};

export default Terminos